server {
    listen 80;
    listen [::]:80;

    server_name jaredgoldberg.org www.jaredgoldberg.org;
    root /var/www/jaredgoldberg.org/current;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ /\. {
        deny all;
    }
}
